Id: Microsoft.VisualStudioCodeInsiders
Version: 1.53.39.7b0cfdd04a
Name: Visual Studio Code - Insiders
Publisher: Microsoft Corporation
Homepage: https://code.visualstudio.com
License: Copyright (c) Microsoft Corporation
Description: Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications. Visual Studio Code is free and available on your favorite platform - Linux, macOS, and Windows.
AppMoniker: vscode-insiders
Commands: code-insiders
Installers: 
    - Arch: x64
      Url: https://az764295.vo.msecnd.net/insider/7b0cfdd04ad530a9c8d782c618afd79290be3d64/VSCodeUserSetup-x64-1.53.0-insider.exe
      InstallerType: inno
      Sha256: b0943079ba9d318fc88278f6808e5fba2c45311879ad005e7258186f6b78602e
