Name: ImageMagick
Publisher: ImageMagick
Id: ImageMagick.ImageMagick
Version: 7.0.10-60
AppMoniker: magick
License: Copyright (c) ImageMagick Studio LLC - derived Apache 2.0 license
Tags: images, bitmap, convert, resize, flip, mirror, rotate, distort, shear, colors, effects, draw
Description: Use ImageMagick® to create, edit, compose, or convert bitmap images.
Homepage: https://imagemagick.org/
LicenseUrl: https://imagemagick.org/script/license.php
Installers:
- Arch: x64
  Url: https://download.imagemagick.org/ImageMagick/download/binaries/ImageMagick-7.0.10-60-Q16-HDRI-x64-dll.exe
  Sha256: A2321839EAB038E9A7632C5F166BA3EABDC868F1FD9663177A143CA0A502436F
  InstallerType: inno
ManifestVersion: 0.1.0
