# ================== General ==================

Id: Spotify.Spotify
Publisher: Spotify AB
Name: Spotify
AppMoniker: spotify
Description: Spotify is a digital music service that gives you access to millions of songs.
Homepage: https://www.spotify.com
Tags: Music, Streaming
License: Copyright © 2012 Spotify AB. All rights reserved.
LicenseUrl: https://www.spotify.com/us/legal/end-user-agreement

# ================= Installer =================

Version: latest # 1.1.48.625
InstallerType: exe
Installers:
  - Arch: neutral
    Url: https://download.scdn.co/SpotifySetup.exe
    Sha256: 2E53451687D82A0CA2046CC81DBD7C257019CBEE7A1E437F0FEC3F4A153B9CC8
    Switches:
      Silent: /Silent
      SilentWithProgress: /Silent
